test:
	python -m tests.cubeInterpolatorTests

experiments:
	python -m experiments

experiments2:
	python -m experiments2

rgi:
	python -m liverDataUtils.regularGridInterpolator

frangi: 
	python -m frangi3DFilter

regionGrowing:
	python -m liverDataUtils.regionGrowing3D